kind: Pod
apiVersion: v1
metadata:
  generateName: jettyj-7d8d67c9df-
  annotations:
    k8s.ovn.org/pod-networks: >-
      {"default":{"ip_addresses":["10.131.0.222/23"],"mac_address":"0a:58:0a:83:00:de","gateway_ips":["10.131.0.1"],"ip_address":"10.131.0.222/23","gateway_ip":"10.131.0.1"}}
    k8s.v1.cni.cncf.io/network-status: |-
      [{
          "name": "ovn-kubernetes",
          "interface": "eth0",
          "ips": [
              "10.131.0.222"
          ],
          "mac": "0a:58:0a:83:00:de",
          "default": true,
          "dns": {}
      }]
    openshift.io/scc: restricted-v2
    seccomp.security.alpha.kubernetes.io/pod: runtime/default
  resourceVersion: '679934'
  name: jettyj-7d8d67c9df-kdvmd
  uid: fbf2c407-8640-4562-9200-fb7f430833f8
  creationTimestamp: '2023-08-01T12:34:21Z'
  managedFields:
    - manager: ip-10-0-165-155
      operation: Update
      apiVersion: v1
      time: '2023-08-01T12:34:21Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            'f:k8s.ovn.org/pod-networks': {}
    - manager: kube-controller-manager
      operation: Update
      apiVersion: v1
      time: '2023-08-01T12:34:21Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:generateName': {}
          'f:labels':
            .: {}
            'f:app': {}
            'f:deployment': {}
            'f:pod-template-hash': {}
          'f:ownerReferences':
            .: {}
            'k:{"uid":"ddb512ce-d0ad-4774-a467-16a4b55f8ec4"}': {}
        'f:spec':
          'f:containers':
            'k:{"name":"jettyk"}':
              .: {}
              'f:image': {}
              'f:imagePullPolicy': {}
              'f:name': {}
              'f:resources': {}
              'f:terminationMessagePath': {}
              'f:terminationMessagePolicy': {}
          'f:dnsPolicy': {}
          'f:enableServiceLinks': {}
          'f:restartPolicy': {}
          'f:schedulerName': {}
          'f:securityContext': {}
          'f:terminationGracePeriodSeconds': {}
    - manager: multus
      operation: Update
      apiVersion: v1
      time: '2023-08-01T12:34:22Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            'f:k8s.v1.cni.cncf.io/network-status': {}
      subresource: status
    - manager: kubelet
      operation: Update
      apiVersion: v1
      time: '2023-08-01T12:34:27Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:status':
          'f:conditions':
            'k:{"type":"ContainersReady"}':
              .: {}
              'f:lastProbeTime': {}
              'f:lastTransitionTime': {}
              'f:status': {}
              'f:type': {}
            'k:{"type":"Initialized"}':
              .: {}
              'f:lastProbeTime': {}
              'f:lastTransitionTime': {}
              'f:status': {}
              'f:type': {}
            'k:{"type":"Ready"}':
              .: {}
              'f:lastProbeTime': {}
              'f:lastTransitionTime': {}
              'f:status': {}
              'f:type': {}
          'f:containerStatuses': {}
          'f:hostIP': {}
          'f:phase': {}
          'f:podIP': {}
          'f:podIPs':
            .: {}
            'k:{"ip":"10.131.0.222"}':
              .: {}
              'f:ip': {}
          'f:startTime': {}
      subresource: status
  namespace: backend
  ownerReferences:
    - apiVersion: apps/v1
      kind: ReplicaSet
      name: jettyj-7d8d67c9df
      uid: ddb512ce-d0ad-4774-a467-16a4b55f8ec4
      controller: true
      blockOwnerDeletion: true
  labels:
    app: jettyk
    deployment: jettyk
    pod-template-hash: 7d8d67c9df
spec:
  restartPolicy: Always
  serviceAccountName: default
  imagePullSecrets:
    - name: default-dockercfg-w6kht
  priority: 0
  schedulerName: default-scheduler
  enableServiceLinks: true
  terminationGracePeriodSeconds: 30
  preemptionPolicy: PreemptLowerPriority
  nodeName: ip-10-0-209-175.ap-northeast-2.compute.internal
  securityContext:
    seLinuxOptions:
      level: 's0:c26,c10'
    fsGroup: 1000670000
    seccompProfile:
      type: RuntimeDefault
  containers:
    - name: jettyk
      image: >-
        image-registry.openshift-image-registry.svc:5000/backend/jettyj@sha256:f9e5ce5974b647a580954d75c57c20c67b7cc6a8a6ab2bef0c17ae30155d6786
      resources: {}
      volumeMounts:
        - name: kube-api-access-rk6md
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      imagePullPolicy: Always
      securityContext:
        capabilities:
          drop:
            - ALL
        runAsUser: 1000670000
        runAsNonRoot: false
  serviceAccount: pleaseroot
  volumes:
    - name: kube-api-access-rk6md
      projected:
        sources:
          - serviceAccountToken:
              expirationSeconds: 3607
              path: token
          - configMap:
              name: kube-root-ca.crt
              items:
                - key: ca.crt
                  path: ca.crt
          - downwardAPI:
              items:
                - path: namespace
                  fieldRef:
                    apiVersion: v1
                    fieldPath: metadata.namespace
          - configMap:
              name: openshift-service-ca.crt
              items:
                - key: service-ca.crt
                  path: service-ca.crt
        defaultMode: 420
  dnsPolicy: ClusterFirst
  tolerations:
    - key: node.kubernetes.io/not-ready
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 300
    - key: node.kubernetes.io/unreachable
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 300
status:
  phase: Running
  conditions:
    - type: Initialized
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2023-08-01T12:34:21Z'
    - type: Ready
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2023-08-01T12:34:27Z'
    - type: ContainersReady
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2023-08-01T12:34:27Z'
    - type: PodScheduled
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2023-08-01T12:34:21Z'
  hostIP: 10.0.209.175
  podIP: 10.131.0.222
  podIPs:
    - ip: 10.131.0.222
  startTime: '2023-08-01T12:34:21Z'
  containerStatuses:
    - restartCount: 0
      started: true
      ready: true
      name: jettyk
      state:
        running:
          startedAt: '2023-08-01T12:34:27Z'
      imageID: >-
        image-registry.openshift-image-registry.svc:5000/backend/jettyk@sha256:f9e5ce5974b647a580954d75c57c20c67b7cc6a8a6ab2bef0c17ae30155d6786
      image: >-
        image-registry.openshift-image-registry.svc:5000/backend/jettyk@sha256:f9e5ce5974b647a580954d75c57c20c67b7cc6a8a6ab2bef0c17ae30155d6786
      lastState: {}
      containerID: 'cri-o://e2d5f8e71a3cfe9986031084a1c774a4da633fd0be02f5dc24c834af85f94ec4'
  qosClass: BestEffort
